### ISSUE TITLE
Transforming iAgree to Json breaks binding

### ISSUE THREAD

**Issue by antgamdia** [isa-group/ideas-json-module#1]
When transforming an iAgree document to JSON and converting it again to iAgree, all bindings seem to be broken.

**Comment by feserafim** [comment]
This issue is related to Binding implementation. When you convert the file content to another format, binding will still reference to previous column and row.
The issue will be solved when binding start working with JSON model.
[https://github.com/isa-group/ideas-studio/issues/93](https://github.com/isa-group/ideas-studio/issues/93)
